#!/bin/bash

awk '/global/{if(found!=1){sub(/\/.*/,"",$2);print$2};found=1}'< <(ip a)

# or as a function
#    myip(){
#        ip a | awk '/global/{if(found!=1){sub(/\/.*/,"",$2); print $2}; found=1}'
#    }

